FROM alpine:3.22 AS build

ARG BEANSTALKD_VERSION=1.13

RUN apk add --no-cache build-base curl
RUN curl -sL https://github.com/beanstalkd/beanstalkd/archive/v${BEANSTALKD_VERSION}.tar.gz | tar xz -C /tmp

WORKDIR /tmp/beanstalkd-${BEANSTALKD_VERSION}
RUN make

FROM alpine:3.22

# the healthcheck opens a tcp socket through bash
RUN apk add --no-cache bash
COPY --from=build /tmp/beanstalkd-*/beanstalkd /usr/bin/beanstalkd

EXPOSE 11300
ENTRYPOINT ["/usr/bin/beanstalkd"]
